### ISSUE TITLE
cog ain't installing properly

### ISSUE THREAD

**Issue by NEUROSHOCK-123** [Gr8z/Legend-Cogs#33]
Exception:
Traceback (most recent call last):
  File "C:\Users\Prabhpreet\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Prabhpreet\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\commands\install.py", line 423, in run
    shutil.rmtree(target_item_dir)
  File "C:\Users\Prabhpreet\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Prabhpreet\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\Prabhpreet\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Prabhpreet\\Desktop\\Bot\\Red-DiscordBot\\lib\\aiohttp\\_websocket.cp35-win_amd64.pyd'

Elixir BotBOT - Today at 6:04 PM
That cog has requirements that I could not install. Check the console for more informations.

**Comment by bobloy** [comment]
A good place to start would be to say which cog you're trying to install
